[2024-09-27T18:33:30.246+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:33:30.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:33:30.253+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:33:30.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:33:33.961+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:33:33.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:33:33.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:33:34.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 3.792 seconds
[2024-09-27T18:34:04.559+0000] {processor.py:186} INFO - Started process (PID=1072) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:04.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:34:04.564+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:34:04.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:04.768+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:34:04.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:34:04.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:04.812+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.260 seconds
[2024-09-27T18:34:35.489+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:35.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:34:35.502+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:34:35.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:36.221+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:34:36.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:34:36.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:34:36.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.886 seconds
[2024-09-27T18:35:07.143+0000] {processor.py:186} INFO - Started process (PID=1076) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:07.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:35:07.157+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:35:07.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:07.499+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:35:07.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:35:07.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:10.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 3.634 seconds
[2024-09-27T18:35:41.819+0000] {processor.py:186} INFO - Started process (PID=1078) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:41.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:35:41.845+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:35:41.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:43.201+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:35:43.186+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:35:43.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:35:43.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 1.619 seconds
[2024-09-27T18:36:13.583+0000] {processor.py:186} INFO - Started process (PID=1209) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:13.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:36:13.591+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:36:13.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:13.999+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:36:13.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:36:14.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:14.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.490 seconds
[2024-09-27T18:36:44.266+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:44.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:36:44.278+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:36:44.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:44.630+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:36:44.624+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:36:44.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:36:44.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.423 seconds
[2024-09-27T18:37:15.003+0000] {processor.py:186} INFO - Started process (PID=1213) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:15.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:37:15.022+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:37:15.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:15.597+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:37:15.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:37:15.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:15.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.665 seconds
[2024-09-27T18:37:46.747+0000] {processor.py:186} INFO - Started process (PID=1215) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:46.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:37:46.786+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:37:46.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:47.677+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:37:47.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:37:47.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:37:47.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 1.014 seconds
[2024-09-27T18:38:17.879+0000] {processor.py:186} INFO - Started process (PID=1217) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:17.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:38:17.887+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:38:17.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:18.070+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:38:18.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:38:18.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:18.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.251 seconds
[2024-09-27T18:38:48.727+0000] {processor.py:186} INFO - Started process (PID=1219) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:48.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:38:48.733+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:38:48.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:48.934+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:38:48.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:38:48.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:38:48.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.269 seconds
[2024-09-27T18:39:19.512+0000] {processor.py:186} INFO - Started process (PID=1221) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:19.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:39:19.516+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:39:19.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:19.665+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:39:19.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:39:19.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:19.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.216 seconds
[2024-09-27T18:39:50.288+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:50.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:39:50.295+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:39:50.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:50.561+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:39:50.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:39:50.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:39:50.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.378 seconds
[2024-09-27T18:40:21.034+0000] {processor.py:186} INFO - Started process (PID=1225) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:21.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:40:21.040+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:40:21.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:21.223+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:40:21.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:40:21.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:21.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.436 seconds
[2024-09-27T18:40:51.887+0000] {processor.py:186} INFO - Started process (PID=1227) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:51.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:40:51.898+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:40:51.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:52.334+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:40:52.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:40:52.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:40:52.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.511 seconds
[2024-09-27T18:41:23.847+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:23.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:41:23.854+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:41:23.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:25.059+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:41:24.778+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:41:25.090+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:25.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 1.483 seconds
[2024-09-27T18:41:55.903+0000] {processor.py:186} INFO - Started process (PID=1231) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:55.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:41:55.912+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:41:55.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:56.907+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:41:56.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:41:56.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:41:57.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 1.121 seconds
[2024-09-27T18:42:27.347+0000] {processor.py:186} INFO - Started process (PID=1233) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:27.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:42:27.351+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:42:27.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:27.695+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:42:27.689+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:42:27.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:27.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 0.397 seconds
[2024-09-27T18:42:58.232+0000] {processor.py:186} INFO - Started process (PID=1235) to work on /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:58.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/utils/Load.py for tasks to queue
[2024-09-27T18:42:58.241+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:42:58.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:59.739+0000] {logging_mixin.py:190} INFO - [2024-09-27T18:42:59.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/utils/Load.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/Load.py", line 4, in <module>
    import airflow.dags.utils.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-27T18:42:59.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/Load.py
[2024-09-27T18:42:59.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/utils/Load.py took 1.698 seconds
