[2024-09-30T22:06:58.279+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:06:58.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:06:58.294+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:06:58.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:07:03.948+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:07:04.132+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:07:04.132+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:07:04.829+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:07:22.396+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:07:28.321+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:07:28.320+0000] {timeout.py:68} ERROR - Process timed out, PID: 50
[2024-09-30T22:07:28.372+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:07:28.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 122, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 110, in extract_youtube_data
    df_YT_data = get_video_details(youtube, video_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extraction.py", line 92, in get_video_details
    response = request.execute()
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/youtube_etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#reducing-dag-complexity, PID: 50
[2024-09-30T22:07:28.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:07:28.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 30.253 seconds
[2024-09-30T22:07:59.010+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:07:59.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:07:59.015+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:07:59.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:08:00.535+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:08:00.553+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:08:00.552+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:08:00.849+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:08:12.595+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:08:25.238+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:08:25.253+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:08:25.300+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:08:25.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:08:25.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:08:25.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 26.365 seconds
[2024-09-30T22:08:55.579+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:08:55.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:08:55.585+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:08:55.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:08:57.121+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:08:57.189+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:08:57.188+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:08:57.571+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:09:09.255+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:09:20.175+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:09:20.196+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:09:20.221+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:09:20.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:09:20.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:09:20.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.775 seconds
[2024-09-30T22:09:50.444+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:09:50.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:09:50.448+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:09:50.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:09:51.311+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:09:51.322+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:09:51.322+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:09:51.608+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:10:03.536+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:10:15.115+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:10:15.142+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:10:15.197+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:10:15.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:10:15.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:10:15.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.838 seconds
[2024-09-30T22:10:23.757+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:10:23.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:10:23.771+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:10:23.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:10:25.305+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:10:25.342+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:10:25.342+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:10:25.711+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:10:38.056+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:10:53.792+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:10:53.791+0000] {timeout.py:68} ERROR - Process timed out, PID: 78
[2024-09-30T22:10:53.859+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:10:53.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 109, in extract_youtube_data
    df_YT_data = get_video_details(youtube, video_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extraction.py", line 91, in get_video_details
    response = request.execute()
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/youtube_etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#reducing-dag-complexity, PID: 78
[2024-09-30T22:10:53.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:10:53.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 30.246 seconds
[2024-09-30T22:11:24.733+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:11:24.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:11:24.744+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:11:24.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:11:26.654+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:11:26.716+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:11:26.715+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:11:27.231+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:11:38.690+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:11:49.828+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:11:49.883+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:11:49.914+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:11:49.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 5, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:11:49.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:11:50.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 25.339 seconds
[2024-09-30T22:12:16.011+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:12:16.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:12:16.015+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:12:16.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:12:17.534+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:12:17.563+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:12:17.562+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:12:18.288+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:12:30.185+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:12:41.635+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:12:41.643+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:12:41.656+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:12:41.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:12:41.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:12:41.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 25.701 seconds
[2024-09-30T22:13:11.965+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:13:11.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:13:11.981+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:13:11.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:13:13.395+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:13:13.404+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:13:13.403+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:13:13.681+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:13:25.393+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:13:35.799+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:13:35.822+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:13:35.851+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:13:35.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:13:35.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:13:35.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.004 seconds
[2024-09-30T22:14:06.805+0000] {processor.py:186} INFO - Started process (PID=103) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:14:06.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:14:06.811+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:14:06.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:14:07.822+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:14:07.835+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:14:07.835+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:14:08.206+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:14:21.222+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:14:32.543+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:14:32.561+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:14:32.582+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:14:32.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:14:32.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:14:32.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 25.834 seconds
[2024-09-30T22:15:03.026+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:15:03.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:15:03.035+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:15:03.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:15:04.651+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:15:04.668+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:15:04.667+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:15:04.966+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:15:18.094+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:15:30.361+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:15:30.390+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:15:30.427+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:15:30.394+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:15:30.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:15:30.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 27.542 seconds
[2024-09-30T22:16:01.002+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:16:01.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:16:01.009+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:16:01.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:16:01.813+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:16:01.836+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:16:01.836+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:16:02.050+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:16:14.290+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:16:25.886+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:16:25.915+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:16:25.948+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:16:25.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:16:25.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:16:26.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 25.334 seconds
[2024-09-30T22:16:56.950+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:16:56.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T22:16:56.960+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:16:56.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:16:58.018+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T22:16:58.032+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:16:58.032+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T22:16:58.255+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T22:17:10.440+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T22:17:21.290+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T22:17:21.307+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:17:21.331+0000] {logging_mixin.py:190} INFO - [2024-09-30T22:17:21.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T22:17:21.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T22:17:21.394+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.457 seconds
[2024-09-30T23:19:02.087+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:19:02.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:19:02.419+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:19:02.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:19:11.718+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:19:11.773+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:19:11.773+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:19:12.219+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:19:26.481+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:19:32.485+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:19:32.484+0000] {timeout.py:68} ERROR - Process timed out, PID: 39
[2024-09-30T23:19:32.585+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:19:32.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 109, in extract_youtube_data
    df_YT_data = get_video_details(youtube, video_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extraction.py", line 91, in get_video_details
    response = request.execute()
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/youtube_etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#reducing-dag-complexity, PID: 39
[2024-09-30T23:19:32.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:19:32.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 30.636 seconds
[2024-09-30T23:20:03.043+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:20:03.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:20:03.050+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:20:03.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:20:05.065+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:20:05.087+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:20:05.086+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:20:05.422+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:20:20.447+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:20:33.081+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:20:33.080+0000] {timeout.py:68} ERROR - Process timed out, PID: 50
[2024-09-30T23:20:33.189+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:20:33.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 109, in extract_youtube_data
    df_YT_data = get_video_details(youtube, video_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extraction.py", line 91, in get_video_details
    response = request.execute()
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/youtube_etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#reducing-dag-complexity, PID: 50
[2024-09-30T23:20:33.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:20:33.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 30.322 seconds
[2024-09-30T23:21:03.517+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:21:03.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:21:03.525+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:21:03.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:21:05.219+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:21:05.241+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:21:05.240+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:21:05.532+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:21:19.850+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:21:33.539+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:21:33.538+0000] {timeout.py:68} ERROR - Process timed out, PID: 64
[2024-09-30T23:21:35.072+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:21:33.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 109, in extract_youtube_data
    df_YT_data = get_video_details(youtube, video_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extraction.py", line 91, in get_video_details
    response = request.execute()
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
                          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 720, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1251, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1103, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/youtube_etl_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.10.2/best-practices.html#reducing-dag-complexity, PID: 64
[2024-09-30T23:21:35.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:21:41.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 37.915 seconds
[2024-09-30T23:22:17.860+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:22:17.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:22:17.878+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:22:17.877+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:22:21.077+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:22:21.113+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:22:21.113+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:22:21.692+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:22:33.624+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:22:45.092+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:22:45.222+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:22:45.288+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:22:45.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:22:45.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:22:45.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 27.862 seconds
[2024-09-30T23:33:11.398+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:33:11.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:33:11.401+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:33:11.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:33:14.216+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:33:14.230+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:33:14.229+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:33:14.440+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:33:25.659+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:33:35.550+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:33:35.601+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:33:35.626+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:33:35.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:33:35.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:33:35.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.289 seconds
[2024-09-30T23:34:05.878+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:34:05.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:34:05.891+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:34:05.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:34:07.156+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:34:07.166+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:34:07.166+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:34:07.355+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:34:18.722+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:34:28.517+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:34:28.528+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:34:28.544+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:34:28.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:34:28.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:34:28.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.727 seconds
[2024-09-30T23:34:59.066+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:34:59.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:34:59.076+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:34:59.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:34:59.912+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:34:59.928+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:34:59.928+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:35:00.220+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:35:12.482+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:35:23.140+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:35:23.159+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:35:23.217+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:35:23.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:35:23.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:35:23.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.885 seconds
[2024-09-30T23:35:54.957+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:35:54.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:35:54.962+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:35:54.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:35:56.372+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:35:56.498+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:35:56.497+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:35:56.828+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:36:07.873+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:36:18.530+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:36:18.637+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:36:18.943+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:36:18.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:36:18.949+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:36:19.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.560 seconds
[2024-09-30T23:37:20.998+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:37:20.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:37:21.004+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:37:21.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:37:22.617+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:37:23.046+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:37:23.046+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:37:23.507+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:37:34.840+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:37:45.207+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:37:45.293+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:37:45.315+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:37:45.294+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:37:45.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:37:45.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 24.396 seconds
[2024-09-30T23:38:16.012+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:38:16.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:38:16.021+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:38:16.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:38:18.008+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:38:18.024+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:38:18.024+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:38:18.277+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:38:30.806+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:38:41.069+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:38:41.081+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:38:41.100+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:38:41.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:38:41.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:38:41.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 25.158 seconds
[2024-09-30T23:39:11.639+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:39:11.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:39:11.644+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:39:11.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:39:12.624+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:39:12.636+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:39:12.635+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:39:12.904+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:39:23.997+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:39:33.948+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:39:33.960+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:39:33.975+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:39:33.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:39:33.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:39:34.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.394 seconds
[2024-09-30T23:40:04.687+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:40:04.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:40:04.691+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:40:04.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:40:05.369+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:40:05.380+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:40:05.380+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:40:05.607+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:40:17.177+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:40:27.404+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:40:27.412+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:40:27.424+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:40:27.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:40:27.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:40:27.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.808 seconds
[2024-09-30T23:40:57.958+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:40:57.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:40:57.962+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:40:57.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:40:58.970+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:40:58.978+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:40:58.977+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:40:59.261+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:41:10.580+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:41:20.481+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:41:20.492+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:41:20.506+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:41:20.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:41:20.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:41:20.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.590 seconds
[2024-09-30T23:41:50.992+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:41:50.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:41:50.997+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:41:50.996+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:41:51.790+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:41:51.797+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:41:51.797+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:41:52.061+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:42:03.573+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:42:13.585+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:42:13.606+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:42:13.627+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:42:13.607+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:42:13.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:42:13.728+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.748 seconds
[2024-09-30T23:42:44.039+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:42:44.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:42:44.043+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:42:44.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:42:45.081+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:42:45.093+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:42:45.093+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:42:45.315+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:42:56.778+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:43:06.721+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:43:06.731+0000] {logging_mixin.py:190} INFO - Error during extraction: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:43:06.745+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:43:06.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 4, in <module>
    import extraction
  File "/opt/airflow/dags/extraction.py", line 121, in <module>
    extract_youtube_data()
  File "/opt/airflow/dags/extraction.py", line 112, in extract_youtube_data
    df_YT_data.to_csv(output_path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/Youtube_Data_Raw.csv'
[2024-09-30T23:43:06.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:43:06.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 22.755 seconds
[2024-09-30T23:43:37.228+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:43:37.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:43:37.233+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:43:37.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:43:38.012+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:43:38.020+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:43:38.020+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:43:38.229+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:43:49.954+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:44:00.032+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:44:00.076+0000] {logging_mixin.py:190} INFO - Data saved to /opt/airflow/data/Youtube_Data_Raw.csv
[2024-09-30T23:44:00.824+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:44:00.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/youtube_etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/youtube_etl_dag.py", line 6, in <module>
    from Load import load_youtube_data
  File "/opt/airflow/dags/Load.py", line 4, in <module>
    import airflow.dags.transformation as transformation
ModuleNotFoundError: No module named 'airflow.dags'
[2024-09-30T23:44:00.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:44:00.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 23.653 seconds
[2024-09-30T23:44:31.338+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:44:31.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:44:31.343+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:44:31.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:44:32.370+0000] {logging_mixin.py:190} INFO - Starting YouTube data extraction...
[2024-09-30T23:44:32.388+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:44:32.387+0000] {__init__.py:49} INFO - file_cache is only supported with oauth2client<4.0.0
[2024-09-30T23:44:32.640+0000] {logging_mixin.py:190} INFO - Channel statistics extracted: 3 channels
[2024-09-30T23:44:44.639+0000] {logging_mixin.py:190} INFO - Extracted 2249 video IDs
[2024-09-30T23:44:55.660+0000] {logging_mixin.py:190} INFO - Extracted data for 2249 videos
[2024-09-30T23:44:55.726+0000] {logging_mixin.py:190} INFO - Data saved to /opt/airflow/data/Youtube_Data_Raw.csv
[2024-09-30T23:44:56.593+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:44:57.191+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:44:57.190+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:44:57.262+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:44:57.261+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:44:57.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 26.149 seconds
[2024-09-30T23:45:27.945+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:45:27.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:45:27.951+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:45:27.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:45:29.394+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:45:29.423+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:45:29.422+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:45:29.452+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:45:29.452+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:45:29.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.693 seconds
[2024-09-30T23:46:00.086+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:00.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:46:00.094+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:00.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:02.502+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:02.537+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:02.536+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:46:02.585+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:02.584+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:46:02.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.802 seconds
[2024-09-30T23:46:33.567+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:33.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:46:33.590+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:33.590+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:37.458+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:37.490+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:37.489+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:46:37.658+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:37.658+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:46:37.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 4.185 seconds
[2024-09-30T23:46:43.094+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:43.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:46:43.098+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:43.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:44.628+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:44.662+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:44.661+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:46:45.057+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:45.057+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:46:45.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.486 seconds
[2024-09-30T23:46:48.063+0000] {processor.py:186} INFO - Started process (PID=143) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:48.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:46:48.069+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:48.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:50.155+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:46:50.182+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:50.181+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:46:50.384+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:46:50.383+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:46:50.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.448 seconds
[2024-09-30T23:47:20.806+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:20.807+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:47:20.810+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:20.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:22.146+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:22.184+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:22.184+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:47:22.373+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:22.372+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:47:22.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.642 seconds
[2024-09-30T23:47:52.962+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:52.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:47:52.966+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:52.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:54.180+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:47:54.428+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:54.428+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:47:54.471+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:47:54.470+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:47:54.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.576 seconds
[2024-09-30T23:48:24.883+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:24.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:48:24.888+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:24.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:26.151+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:26.181+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:26.180+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:48:26.211+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:26.211+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:48:26.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.405 seconds
[2024-09-30T23:48:56.678+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:56.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:48:56.682+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:56.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:58.583+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:48:58.623+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:58.622+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:48:58.698+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:48:58.698+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:48:58.797+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.131 seconds
[2024-09-30T23:49:29.405+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:49:29.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:49:29.409+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:49:29.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:49:30.501+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:49:30.529+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:49:30.528+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:49:30.556+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:49:30.556+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:49:30.615+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.215 seconds
[2024-09-30T23:50:01.042+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:01.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:50:01.048+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:01.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:02.304+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:02.332+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:02.332+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:50:02.469+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:02.469+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:50:02.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.524 seconds
[2024-09-30T23:50:32.779+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:32.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:50:32.782+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:32.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:34.362+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:50:34.402+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:34.401+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:50:34.581+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:50:34.580+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:50:34.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.893 seconds
[2024-09-30T23:51:05.029+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:05.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:51:05.034+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:05.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:06.743+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:06.951+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:06.950+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:51:07.010+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:07.009+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:51:07.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.114 seconds
[2024-09-30T23:51:38.080+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:38.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:51:38.094+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:38.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:41.479+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:51:41.705+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:41.704+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:51:41.788+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:51:41.786+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:51:41.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 3.825 seconds
[2024-09-30T23:52:13.382+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:13.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:52:13.398+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:13.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:17.644+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:17.717+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:17.716+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:52:17.777+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:17.776+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:52:17.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 4.537 seconds
[2024-09-30T23:52:48.368+0000] {processor.py:186} INFO - Started process (PID=188) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:48.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:52:48.375+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:48.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:50.875+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:52:50.904+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:50.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:52:50.957+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:52:50.956+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:52:51.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.758 seconds
[2024-09-30T23:53:21.822+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:53:21.824+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:53:21.832+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:53:21.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:53:28.567+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:53:28.799+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:53:28.798+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:53:28.930+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:53:28.929+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:53:29.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 7.377 seconds
[2024-09-30T23:54:01.071+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:01.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:54:01.079+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:01.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:04.080+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:04.235+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:04.234+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:54:04.318+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:04.318+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:54:04.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 3.361 seconds
[2024-09-30T23:54:34.833+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:34.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:54:34.839+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:34.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:37.524+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:54:37.597+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:37.596+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:54:37.881+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:54:37.880+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:54:37.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 3.154 seconds
[2024-09-30T23:55:08.252+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:08.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:55:08.256+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:08.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:10.482+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:10.536+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:10.534+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:55:10.718+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:10.717+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:55:10.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.586 seconds
[2024-09-30T23:55:41.281+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:41.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:55:41.288+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:41.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:43.034+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:55:43.133+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:43.132+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:55:43.390+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:55:43.389+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:55:43.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.193 seconds
[2024-09-30T23:56:13.973+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:13.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:56:13.988+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:13.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:15.902+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:16.167+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:16.166+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:56:16.199+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:16.199+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:56:16.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.337 seconds
[2024-09-30T23:56:46.698+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:46.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:56:46.704+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:46.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:48.895+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:56:49.125+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:49.124+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:56:49.169+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:56:49.168+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:56:49.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.629 seconds
[2024-09-30T23:57:19.853+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:19.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:57:19.861+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:19.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:25.637+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:25.741+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:25.740+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:57:26.109+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:26.108+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:57:27.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 8.092 seconds
[2024-09-30T23:57:58.274+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:58.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:57:58.279+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:58.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:59.704+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:57:59.742+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:59.741+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:57:59.770+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:57:59.770+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:57:59.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 1.576 seconds
[2024-09-30T23:58:30.191+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:58:30.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:58:30.200+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:58:30.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:58:32.770+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:58:32.810+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:58:32.809+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:58:32.864+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:58:32.864+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:58:32.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.808 seconds
[2024-09-30T23:59:04.653+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:04.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:59:04.670+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:04.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:10.085+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:10.160+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:10.157+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:59:10.248+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:10.248+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:59:10.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 5.729 seconds
[2024-09-30T23:59:41.030+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:41.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/youtube_etl_dag.py for tasks to queue
[2024-09-30T23:59:41.036+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:41.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:42.938+0000] {processor.py:925} INFO - DAG(s) 'youtube_etl_dag' retrieved from /opt/airflow/dags/youtube_etl_dag.py
[2024-09-30T23:59:43.235+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:43.234+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2024-09-30T23:59:43.286+0000] {logging_mixin.py:190} INFO - [2024-09-30T23:59:43.286+0000] {dag.py:4180} INFO - Setting next_dagrun for youtube_etl_dag to 2024-09-29 00:00:00+00:00, run_after=2024-09-30 00:00:00+00:00
[2024-09-30T23:59:43.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/youtube_etl_dag.py took 2.363 seconds
